artists:
  - "Anitta"
  - "Luísa Sonza"
  - "Djavan"
  - "Jorge Ben Jor"
  - "Liniker"

playlists:
  - id: "1tOrLjlSB49vMA9jasoat8"
    name: "Top Brasil 2026"
  - id: "6u67VfC7voYC3PFazJixAK"
    name: "MPB Barzinho"
  - id: "0gMdDTXoAiqt6mc4XwTNnX"
    name: "Funk Brasileiro 2026"
